name: lunaR CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install R
      run: sudo apt-get install -y r-base libfftw3-dev

    - name: Install luna-base
      run: |
        cd $HOME
        git clone http://github.com/remnrem/luna-base.git
        cd luna-base
        make
        echo $GITHUB_WORKSPACE
        cd ..
        
    - name: make lunaR
      run: |
        sudo R -e "install.packages('git2r', repos='https://cloud.r-project.org')"
        sudo R -e "install.packages('plotrix', repos='https://cloud.r-project.org')"
        sudo R -e "install.packages('geosphere', repos='https://cloud.r-project.org')"
        sudo R -e "install.packages('geosphere', repos='https://cloud.r-project.org')"
        sudo R -e "install.packages('data.table', repos='https://cloud.r-project.org')"
        sudo R -e "install.packages('shiny', repos='https://cloud.r-project.org')"
        sudo R -e "install.packages('DT', repos='https://cloud.r-project.org')"
        sudo R -e "install.packages('shinyFiles', repos='https://cloud.r-project.org')"
        sudo R -e "install.packages('xtable', repos='https://cloud.r-project.org')"
        sudo R -e "install.packages('shinydashboard', repos='https://cloud.r-project.org')"
        sudo LUNA_BASE=${HOME}/luna-base/ R CMD INSTALL ${GITHUB_WORKSPACE}
